### ISSUE TITLE
Page isn't up anymore

### ISSUE THREAD

**Issue by Trevoke** [emacsfodder/emacs-theme-editor#2]
:panda_face:

**Comment by jasonm23** [comment]
Note that this is an old Emacs 22 color-theme.el style theme editor.

Not compatible with the new deftheme used in current Emacs versions.

The link isn't broken, there's just something up with Github's SSL certificates (or rather google thinks there is.)

**Comment by jasonm23** [comment]
Modifying link to use https://

**Comment by jasonm23** [comment]
Oops! Needed to move link to emacsfodder

**Comment by Trevoke** [comment]
Still neat, thanks for the fix :)

**Comment by jasonm23** [comment]
Changing it to do Emacs defteme isn't too hard.

Have a look at theme.js

The main difference is all "elements" are defined with an a-list.
