### ISSUE TITLE
Package lacks a file header

### ISSUE THREAD

**Issue by jeremiah** [emacsfodder/emacs-theme-editor#3]
Hi,

I'm installing a generated theme from the emacs-theme-editor on the emacsfodder site but I'm getting this error message when I install the theme-theme.el file;

Package lacks a file header

I wonder if the theme generator might generate the file header?

**Comment by jasonm23** [comment]
The package headers are part of the comment section at the top.

You are missing one - see this manual entry

http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

**Comment by jeremiah** [comment]
Yeah, that URL was what I was reading while filing this issue. :-)

It seems the comment section was missing from the downloaded file, perhaps that can get added?

This is the generated file I received;
(Gist) https://gist.github.com/jeremiah/7ab8e0cf6ff3291ab399

**Comment by jasonm23** [comment]
Seems fair, however.

I didn't add this in the re-boot of the theme-editor, because it's a lot of plain editing that you'll do outside Emacs, which is unpleasant.  The theme editor isn't mean to be the last place you touch the theme file, it's just meant to get you set up with a core palette.

I hope you understand the rationale.

**Comment by jeremiah** [comment]
Ah, that makes perfect sense. I agree, the core palette is the interesting code and what most folks are after. :+1:

**Comment by jasonm23** [comment]
Just re-opening this as I'm re-working the code for the theme editor as Es6 and culling the old coffeescript guts.

**Comment by jasonm23** [comment]
it will add the following package header as boiler-plate...

```
;;; {{name}}-theme.el --- {{Name}}
;;; Version: 1.0
;;; Commentary:
;;; A theme called {{Name}}
;;; Code:

```

**Comment by jasonm23** [comment]
(also adding)

```
;;; {{name}}-theme.el ends here
```
as a footer

**Comment by jasonm23** [comment]
06ceb5d
